DELETE FROM RATING;
DELETE FROM GENRE;
ALTER TABLE RATING ALTER COLUMN RATING_ID RESTART WITH 1;
ALTER TABLE GENRE ALTER COLUMN GENRE_ID RESTART WITH 1;
INSERT INTO RATING (RATING_NAME)
VALUES ('G'), ('PG'), ('PG-13'), ('R'), ('NC-17');
INSERT INTO GENRE (GENRE_NAME)
VALUES ('Комедия'), ('Драма'), ('Мультфильм'), ('Триллер'), ('Документальный'), ('Боевик');