DELETE FROM RATING;
DELETE FROM GENRE;
DELETE FROM FRIENDS_LIST;
DELETE FROM FRIENDSHIP_STATUS;
DELETE FROM USER_LIST;

ALTER TABLE RATING ALTER COLUMN RATING_ID RESTART WITH 1;
ALTER TABLE GENRE ALTER COLUMN GENRE_ID RESTART WITH 1;
ALTER TABLE FRIENDS_LIST ALTER COLUMN FRIEND_RECORD_ID RESTART WITH 1;
ALTER TABLE FRIENDSHIP_STATUS ALTER COLUMN STATUS_ID RESTART WITH 1;
ALTER TABLE USER_LIST ALTER COLUMN USER_ID RESTART WITH 1;

INSERT INTO RATING (RATING_NAME)
VALUES ('G'), ('PG'), ('PG-13'), ('R'), ('NC-17');
INSERT INTO GENRE (GENRE_NAME)
VALUES ('Комедия'), ('Драма'), ('Мультфильм'), ('Триллер'), ('Документальный'), ('Боевик');
INSERT INTO FRIENDSHIP_STATUS (STATUS_NAME)
VALUES ('REQUEST_SENT');